#!/usr/bin/env python3
"""
normalize.py — Convert any chat export format to MemPalace transcript format.

Supported:
    - Plain text with > markers (pass through)
    - Claude.ai JSON export
    - ChatGPT conversations.json
    - Claude Code JSONL (with tool_use/tool_result block capture)
    - OpenAI Codex CLI JSONL
    - Gemini CLI JSONL (~/.gemini/tmp/<project_hash>/chats/session-*.jsonl)
    - Pi agent JSONL
    - Gemini CLI / Google AI Studio JSON sessions (contents / messages / flat list)
    - Continue.dev session JSON (~/.continue/sessions/*.json)
    - Slack JSON export
    - Plain text (pass through for paragraph chunking)

No API key. No internet. Everything local.
"""

import functools
import json
import os
import re
import stat
import sys
from pathlib import Path
from typing import NamedTuple, Optional

# Provenance footer appended to Slack transcript output so downstream consumers
# know the speaker roles are positionally assigned, not verified.
_SLACK_PROVENANCE_FOOTER = (
    "\n[source: slack-export | multi-party chat — speaker roles are positional, not verified]"
)


# ─── Noise stripping ─────────────────────────────────────────────────────
# Claude Code and other tools inject system tags, hook output, and UI chrome
# into transcripts. These waste drawer space and pollute search results.
#
# Verbatim is sacred — every pattern here is anchored to line boundaries and
# refuses to cross blank lines, so a stray unclosed tag in one message can
# never eat content from neighboring messages. When in doubt, leave text
# alone.

_NOISE_TAGS = (
    "system-reminder",
    "command-message",
    "command-name",
    # Rest of the slash-command envelope Claude Code injects around every
    # slash-command invocation (#1333). Before this only the middle three tags
    # were covered, so the caveat, args, and captured stdout/stderr streams
    # leaked into drawers verbatim. ``local-command-stderr`` is included even
    # though the #1333 root-cause sketch listed only five tags -- it is
    # emitted for commands that write to stderr and was found in real
    # transcripts alongside the other five.
    "command-args",
    "local-command-caveat",
    "local-command-stdout",
    "local-command-stderr",
    "task-notification",
    "user-prompt-submit-hook",
    "hook_output",
)


def _tag_pattern(name: str) -> "re.Pattern[str]":
    # Opening tag must begin a line (optionally after a `> ` blockquote marker,
    # since _messages_to_transcript prefixes lines with `> `). The body is lazy
    # and halts at the next opening tag of the same name, so a dangling open tag
    # can't span past the next same-tag block -- while still allowing blank
    # lines *inside* the tag (multi-paragraph <local-command-stdout> output,
    # tables, stack traces; #1333). The lookahead checks for whitespace or `>`
    # immediately after the name (not a bare `\b`), so `<command-args>` doesn't
    # false-match a prefix of a longer tag name like `<command-args-extended>`
    # (`\b` alone triggers between "s" and "-", which are a word/non-word pair).
    # Combined with the line-start anchor this keeps a stray tag from eating
    # neighbouring messages. Closing tag eats optional trailing whitespace +
    # newline.
    return re.compile(
        rf"(?m)^(?:> )?<{name}(?:\s[^>]*)?>" rf"(?:(?!<{name}[\s>])[\s\S])*?" rf"</{name}>[ \t]*\n?"
    )


_NOISE_TAG_PATTERNS = [_tag_pattern(t) for t in _NOISE_TAGS]

# Strings that identify an entire noise line when found at its start.
# Matched case-sensitively and anchored to line-start so user prose mentioning
# e.g. "current time:" in a sentence is untouched.
_NOISE_LINE_PREFIXES = (
    "CURRENT TIME:",
    "VERIFIED FACTS (do not contradict)",
    "AGENT SPECIALIZATION:",
    "Checking verified facts...",
    "Injecting timestamp...",
    "Starting background pipeline...",
    "Checking emotional weights...",
    "Auto-save reminder...",
    "Checking pipeline...",
    "MemPalace auto-save checkpoint.",
)

_NOISE_LINE_PATTERNS = [
    re.compile(rf"(?m)^(?:> )?{re.escape(p)}.*\n?") for p in _NOISE_LINE_PREFIXES
]

# Claude Code TUI hook-run chrome, e.g. "Ran 2 Stop hook", "Ran 1 PreCompact hook".
# Line-anchored, case-sensitive, explicit hook names — prose like
# "our CI has a stop hook" stays intact.
_HOOK_LINE_RE = re.compile(
    r"(?m)^(?:> )?Ran \d+ (?:Stop|PreCompact|PreToolUse|PostToolUse|UserPromptSubmit|Notification|SessionStart|SessionEnd) hook[s]?.*\n?"
)

# "… +N lines" collapsed-output marker, line-anchored.
_COLLAPSED_LINES_RE = re.compile(r"(?m)^(?:> )?…\s*\+\d+ lines.*\n?")

# Claude Code's own literal placeholder for a Bash call that produced no
# stdout/stderr. Deliberately NOT line-anchored, unlike the patterns above:
# flattened tool_result forms embed it mid-line (e.g. ``[tool_result:
# "(Bash completed with no output)"]``), and the exact parenthesized
# literal is generated by Claude Code itself, so the only prose casualty
# is text *documenting* the placeholder — an accepted, marginal loss.
# Promoted from a user noise-patterns file after confirmation against a
# ~725-transcript corpus (2026-07).
_BASH_NO_OUTPUT_RE = re.compile(r"\(Bash completed with no output\)")

# ``gh run view --log-failed`` / ``gh run view --log`` job-log chrome,
# captured via the Bash tool. Every line comes back prefixed
# ``<job-name><TAB>UNKNOWN STEP<TAB><ISO-8601 timestamp>Z <log text>`` —
# dozens to ~100 lines per call. Strips the job/step/timestamp prefix,
# keeps the arrow marker (if present) and the real log text. The
# job-name field is ``[^\t\n]+`` (not ``\S+``) because real job names
# contain spaces; the optional BOM before the timestamp appears in real
# captures. Same deterministic-tool-chrome rationale as the ANSI
# patterns; confirmed in 41 real transcripts (2026-07).
_GH_RUN_LOG_PREFIX_RE = re.compile(
    r"(?m)^(→ )?[^\t\n]+\tUNKNOWN STEP\t(?:\ufeff?\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z )?"
)

# ANSI escape sequences that Claude Code's Bash tool preserves verbatim from
# terminal output (#1333). These are not a data-integrity hazard the way an
# embedded NUL byte is -- every byte here is well-formed, printable-adjacent
# text a terminal happens to interpret specially, not binary garbage. The
# harm is purely on the consumption side: each escape costs several BPE
# tokens for no semantic content, they interleave with and obscure the word
# boundaries either side of them, and they dilute search relevance. Unlike
# the tag patterns above these are NOT line-anchored -- they are anchored on
# the literal ESC byte (0x1B), a control character that never appears in
# legitimate prose, so text that merely *names* a sequence like "[1m" or
# "ESC[0m" survives untouched. All three are ReDoS-safe by construction
# (disjoint / negated character classes, no overlapping nested quantifiers).
#
# CSI (Control Sequence Introducer): ESC [ , parameter bytes (0-9 and `;`),
# one final byte (0x40-0x7E). Covers all SGR color/style codes (the dominant
# Bash-output noise) plus cursor movement/erase.
#
# The parameter-byte group requires ONE OR MORE bytes (`+`, not `*`), and
# drops ECMA-48's optional "intermediate bytes" (0x20-0x2F) entirely. Both
# choices trade spec completeness for truncation-safety: the final-byte
# class (0x40-0x7E) covers nearly every letter, so a genuinely *empty*-param
# CSI (`ESC[` followed immediately by a letter) is indistinguishable from a
# truncated CSI immediately followed by real prose that happens to start
# with a letter -- and real captured tool output does get truncated
# mid-write (a background process's redirected stdout racing its reader).
# Requiring a digit/`;` first closes the highest-frequency failure shape
# (zero-param truncation immediately followed by an ordinary word) at the
# cost of no longer stripping the rare genuinely-empty-param sequences
# (e.g. bare `ESC[H`, cursor-home with no row/col) -- left as harmless
# unstripped noise rather than risking eating a real word's first letter.
# Dropping the intermediate-byte class removes the same ambiguity for
# space/punctuation runs (0x20-0x2F includes space and `!"#$%&'()*+,-./`,
# all common in real prose) between the parameters and the final byte.
_ANSI_CSI_RE = re.compile(r"\x1b\[[0-9;]+[\x40-\x7e]")
# OSC (Operating System Command): ESC ] , string payload, terminated by BEL
# (0x07) or ST (ESC \). Covers hyperlinks (ESC]8;;URL BEL) and window titles.
#
# The payload class excludes ESC itself, so a truncated OSC's greedy scan
# can never jump *over* a later, unrelated escape sequence to reach a more
# distant terminator -- it always stops at the very next ESC byte and
# either finds a valid terminator right there or the whole match fails.
# The one residual risk this doesn't close: a genuine bare BEL (0x07)
# appearing later in real prose would still be consumed as a false
# terminator, eating everything in between. Accepted rather than dropping
# legacy BEL-terminated OSC support -- BEL essentially never appears in
# real captured text, unlike the letters/punctuation that made the CSI
# case common.
_ANSI_OSC_RE = re.compile(r"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)")
# Everything else ECMA-48 defines as a *simple* escape sequence: ESC followed
# by exactly one more byte, no payload. Covers the VT100-common "nF" range
# (0x30-0x3F -- e.g. ESC 7 / ESC 8, DECSC/DECRC save/restore cursor), the "Fe"
# set (0x40-0x5F) minus CSI/OSC's own introducers ('[' 0x5B, ']' 0x5D --
# already consumed above so order doesn't matter here), and the "Fs" set
# (0x60-0x7E, independent control functions). The one that motivated adding
# this: watch-mode dev tools (tsx watch, nodemon) emit ESC c -- RIS, full
# terminal reset -- before reprinting output on a file-change restart. A
# background process's redirected stdout/stderr can pick this up verbatim;
# a captured Bash tool_result carrying it is ordinary, not exotic.
_ANSI_SIMPLE_RE = re.compile(r"\x1b[\x30-\x5a\x5c\x5e-\x7e]")
# Orphan SGR bodies: the printable residue left after Claude Code strips the
# ESC byte (0x1B) but preserves the rest of a CSI SGR sequence.  The corpus
# contains zero real ESC bytes (Claude Code already strips them); what
# remains is bare ``[31m``, ``[0m``, ``[38;5;173m`` etc. — 54 k hits across
# 55 transcript files, all noise.  Six negative lookbehinds protect source
# code that legitimately writes about escape sequences (``\x1b[…``,
# ``\033[…``, ``\e[…``, ``^[[…``, ``ESC[…``), and a negative lookahead
# ``(?!\])`` protects array subscripts like ``arr[1m]``.
_ORPHAN_SGR_RE = re.compile(
    r"(?<!\x1b)(?<!\^\[)(?<!\\e)(?<!\\033)(?<!\\x1b)(?<!ESC)"
    r"\[[0-9]{1,3}(?:;[0-9]{1,3}){0,5}m(?!\])"
)


@functools.lru_cache(maxsize=1)
def _dynamic_noise_patterns() -> tuple:
    """Load and compile user-supplied strip_noise() substitution rules.

    This is the "grep pattern file, but for substitutions" hook: an
    external, user-editable file of extra strip/replace rules, read at
    invocation instead of hardcoded, for noise that's specific to one
    person's environment or corpus (absolute file paths, a particular
    tool's boilerplate output, etc.) rather than universal across every
    Claude Code install the way the tag/ANSI patterns above are.

    Source file resolution (see MempalaceConfig.noise_patterns_file):
    ``MEMPALACE_NOISE_PATTERNS_FILE`` env var, then ``noise_patterns_file``
    in ``~/.mempalace/config.json``, then ``~/.mempalace/noise_patterns.txt``
    if that file happens to exist. Nothing configured -> empty tuple ->
    strip_noise() behaves exactly as it did before this existed.

    File format: one rule per line, ``<regex><TAB><replacement>``. ``#``
    lines and blank lines are skipped. Replacement follows Python
    ``re.sub`` semantics (backreferences like ``\\1`` work; an empty
    replacement deletes the match). For case-insensitive matching, prefix
    the pattern with ``(?i)`` -- standard Python inline-flag syntax --
    rather than a separate flags column, to keep the file two-column-simple.
    A line with an invalid regex or missing tab is skipped with a warning
    on stderr rather than aborting the whole mine; one bad line in a
    hand-edited file shouldn't take down ingestion.

    Cached for the process lifetime (functools.lru_cache): this runs once
    per MESSAGE during mining, not once per file or once per mine
    invocation, so re-reading and recompiling the file on every call would
    be a measurable cost across a large transcript corpus. In practice
    this means a change to the file takes effect on the next `mempalace
    mine` invocation (a fresh, short-lived process) but NOT mid-session in
    the long-running MCP server without a restart -- same trade-off
    entity_detector.py already makes for its COCA/known-systems data files.
    """
    try:
        from .config import MempalaceConfig

        path = MempalaceConfig().noise_patterns_file
    except Exception:
        path = None
    if not path:
        return ()

    try:
        raw_lines = Path(path).read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError as exc:
        print(f"WARNING: could not read noise_patterns_file {path}: {exc}", file=sys.stderr)
        return ()

    compiled = []
    for lineno, raw_line in enumerate(raw_lines, 1):
        line = raw_line.rstrip("\n")
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "\t" not in line:
            print(
                f"WARNING: {path}:{lineno}: no tab separator between pattern and "
                f"replacement, skipping: {line!r}",
                file=sys.stderr,
            )
            continue
        pattern_str, replacement = line.split("\t", 1)
        try:
            compiled.append((re.compile(pattern_str), replacement))
        except re.error as exc:
            print(f"WARNING: {path}:{lineno}: invalid regex, skipping: {exc}", file=sys.stderr)
    return tuple(compiled)


# ── ASCII-armored binary ("armor") — universal, not machine-specific ──
# Payloads of binary encoded as text: data-URIs, bundler-packed blobs,
# PEM/MIME bodies, and the residue binary leaves after decoding
# (errors="replace"). These carry no recall value — no user will ever
# search for the middle of a base64 run — and they poison embeddings.
# Corpus-validated 2026-07-11 (13,878 real prose/code/transcript chunks:
# zero false strips; a 1.6MB bundler payload and binary font dumps:
# fully removed). Deletions target the payload only; PEM headers and
# surrounding prose survive as searchable context.
_ARMOR_PATTERNS = (
    # data-URI payloads (inline images/fonts) — delete the whole URI.
    (re.compile(r"data:[\w.+-]+/[\w.+-]+;base64,[A-Za-z0-9+/=]+"), ""),
    # Any unbroken base64-alphabet run >= 300 chars (bundler blobs,
    # embedded binaries). Real tokens stay far under this (sha512-base64
    # is 88 chars); minified JS breaks the class with punctuation.
    (re.compile(r"[A-Za-z0-9+/]{300,}={0,2}"), ""),
    # Line-wrapped base64 (PEM / MIME style: 3+ consecutive 56-80-char
    # lines of pure base64) — evades the unbroken-run rule because each
    # newline breaks the run. Also secret-hygiene: key material should
    # not be searchable.
    (re.compile(r"(?:[A-Za-z0-9+/]{56,80}\n){3,}[A-Za-z0-9+/]*={0,2}\n?"), " "),
    # Runs of U+FFFD — what undecodable bytes become under
    # errors="replace". A single lone one is kept (could be one real
    # encoding hiccup inside genuine text); runs mean binary.
    (re.compile("(?:\ufffd[ \t]?){2,}"), " "),
    # Runs of C0/C1 control characters (tab/LF/CR excluded) — binary
    # decoded latin-1-style. Collapsed to one space, not deleted, so
    # adjacent legitimate tokens don't get welded together.
    (re.compile(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]{2,}"), " "),
)

# ── Secrets screen — high-confidence credential shapes ────────────────
# Live credentials captured in transcripts/tool output must never become
# searchable memory. Only PREFIX/STRUCTURE-KEYED shapes are matched
# (vendor-chosen sentinels like AKIA/ghp_/xoxb-): each pattern's anchor
# is a string that essentially cannot occur in prose by accident.
# Deliberately NO generic entropy/keyword detection (the detect-secrets
# style "high-entropy string after the word password") — in a memory
# system a false strip is destroyed recall, so FP-prone detectors are
# excluded by design. Rule shapes follow the secretlint/gitleaks/
# detect-secrets ecosystems. Replacement is a visible marker, not
# deletion: "there was a credential here" is legitimate, searchable
# context; the credential itself is not.
_SECRET_PATTERNS = (
    # AWS access key IDs (AKIA=long-lived, ASIA=STS, ABIA/ACCA variants).
    (re.compile(r"\b(?:AKIA|ASIA|ABIA|ACCA)[A-Z0-9]{16}\b"), "[redacted:aws-key-id]"),
    # GitHub tokens: classic (ghp_/gho_/ghu_/ghs_/ghr_) and fine-grained.
    (re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,255}\b"), "[redacted:github-token]"),
    (re.compile(r"\bgithub_pat_[A-Za-z0-9_]{22,255}\b"), "[redacted:github-token]"),
    # GitLab personal access tokens.
    (re.compile(r"\bglpat-[A-Za-z0-9_-]{20,}\b"), "[redacted:gitlab-token]"),
    # OpenAI / Anthropic style keys. {32,} keeps short "sk-" prefixed
    # identifiers (e.g. skeleton-loader CSS classes) out of scope.
    (re.compile(r"\bsk-(?:ant-|proj-)?[A-Za-z0-9_-]{32,}\b"), "[redacted:api-key]"),
    # Slack tokens + incoming-webhook paths.
    (re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}\b"), "[redacted:slack-token]"),
    (
        re.compile(r"hooks\.slack\.com/services/T[A-Za-z0-9]+/B[A-Za-z0-9]+/[A-Za-z0-9]+"),
        "hooks.slack.com/services/[redacted:slack-webhook]",
    ),
    # Stripe secret/restricted keys (live AND test — test keys still
    # grant API access to the test-mode account).
    (re.compile(r"\b[rs]k_(?:live|test)_[A-Za-z0-9]{16,}\b"), "[redacted:stripe-key]"),
    # Google API keys.
    (re.compile(r"\bAIza[A-Za-z0-9_-]{35}\b"), "[redacted:google-api-key]"),
    # npm automation tokens.
    (re.compile(r"\bnpm_[A-Za-z0-9]{36}\b"), "[redacted:npm-token]"),
    # PyPI upload tokens (macaroon with fixed b64 "pypi.org" prefix).
    (re.compile(r"\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{20,}\b"), "[redacted:pypi-token]"),
    # SendGrid API keys (SG.<22>.<43>).
    (re.compile(r"\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b"), "[redacted:sendgrid-key]"),
    # Twilio API key SIDs (SK + 32 hex).
    (re.compile(r"\bSK[a-f0-9]{32}\b"), "[redacted:twilio-key]"),
    # JWTs — three dot-joined base64url segments, first two decoding
    # from the literal '{"' ("eyJ"). Session tokens in captured curl/
    # header output are credentials for their lifetime.
    (
        re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b"),
        "[redacted:jwt]",
    ),
    # Authorization: Bearer <token> header captures. {30,} floor keeps
    # doc placeholders (YOUR_TOKEN, $TOKEN, <token>) out of scope.
    (re.compile(r"(?i)\bBearer\s+[A-Za-z0-9_\-.=~+/]{30,}"), "Bearer [redacted:bearer-token]"),
)


def strip_noise(text: str) -> str:
    """Remove system tags, hook output, and Claude Code UI chrome from text.

    All patterns are line-anchored. User prose that happens to mention these
    strings inline (e.g., documenting them) is preserved verbatim.
    """
    for pat in _NOISE_TAG_PATTERNS:
        text = pat.sub("", text)
    for pat in _NOISE_LINE_PATTERNS:
        text = pat.sub("", text)
    text = _HOOK_LINE_RE.sub("", text)
    text = _COLLAPSED_LINES_RE.sub("", text)
    text = _BASH_NO_OUTPUT_RE.sub("", text)
    text = _GH_RUN_LOG_PREFIX_RE.sub(r"\1", text)
    for pat, repl in _ARMOR_PATTERNS:
        text = pat.sub(repl, text)
    for pat, repl in _SECRET_PATTERNS:
        text = pat.sub(repl, text)
    # Strip the Claude Code collapsed-output chrome "[N tokens] (ctrl+o to expand)".
    # Narrow shape — a bare "(ctrl+o to expand)" in user prose stays intact.
    text = re.sub(r"\s*\[\d+\s+tokens?\]\s*\(ctrl\+o to expand\)", "", text)
    # Strip ANSI escape sequences from terminal / Bash-tool output (#1333).
    # Applied after tag removal so escapes nested inside a stripped envelope
    # (e.g. <local-command-stdout>) are already gone with the tag.
    text = _ANSI_OSC_RE.sub("", text)
    text = _ANSI_CSI_RE.sub("", text)
    text = _ANSI_SIMPLE_RE.sub("", text)
    text = _ORPHAN_SGR_RE.sub("", text)
    # User-supplied additional substitution rules, loaded dynamically from
    # a file rather than hardcoded (see _dynamic_noise_patterns). Applied
    # after the built-in cleanup above so custom rules act on already-
    # cleaned text, and before the blank-line collapse below so any blank
    # runs they create get tidied up too. No-op (empty tuple) unless a
    # patterns file is actually configured.
    for pattern, replacement in _dynamic_noise_patterns():
        text = pattern.sub(replacement, text)
    # Collapse runs of blank lines created by the removals
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip()


# Evidence floor for is_textlike(): below this length the two ratios are
# too noisy to accuse a chunk of being armor, so we default to keeping it
# (verbatim principle: when in doubt, store).
_TEXTLIKE_MIN_EVIDENCE = 100


def is_textlike(
    chunk: str,
    *,
    ws_min: float = 0.02,
    alnum_max: float = 0.95,
) -> bool:
    """True when a chunk reads as prose/code, False when it reads as armor.

    "Armor" = ASCII-armored binary (base64/hex payloads, bundler-packed
    blobs, font/image dumps decoded to text). Its statistical signature is
    the CONJUNCTION of near-zero whitespace AND near-pure alphanumeric
    content. Real dense text fails at most one side: packed single-line
    JSON has ~0 whitespace but is punctuation-rich (alnum ~0.7-0.85);
    minified JS likewise; prose and CJK have normal whitespace. The
    conjunction is what keeps them safe — do not relax it to a vote.

    Pure predicate: never mutates content, decides nothing by itself.
    Callers (miners/chunkers) choose whether to skip a failing chunk, and
    should count skips visibly — silent truncation must never look like
    full coverage.

    Empirical basis (2026-07-11, real mixed corpus): 13,878 prose/code/
    transcript/wireframe chunks → 1 flagged (a PEM private-key body, a
    true positive); raw armor corpora (a 1.6MB bundler payload, binary
    font dumps read as text) → 88-91% flagged. Chunks shorter than
    _TEXTLIKE_MIN_EVIDENCE pass unconditionally: too little signal to
    accuse. The empty string is not text.
    """
    n = len(chunk)
    if n == 0:
        return False
    if n < _TEXTLIKE_MIN_EVIDENCE:
        return True
    ws = sum(c.isspace() for c in chunk) / n
    alnum = sum(c.isalnum() for c in chunk) / n
    return not (ws < ws_min and alnum > alnum_max)


def _read_source_file(filepath: str) -> str:
    """Hardened raw-content read shared by normalize() and any caller that
    needs the exact same raw content it would read (e.g. convo_miner's
    incremental-mining cursor computation, which needs raw JSONL lines
    alongside the parsed transcript). Rejects symlinks, requires a
    regular file, and caps size at 500 MB.

    Centralizing this is what lets a caller read a file ONCE and hand
    the same string to both normalize() and a second consumer, instead
    of two independent reads that could observe different content if the
    file is actively being appended to between them (a real scenario for
    an in-progress Claude Code session) -- and without this, a second,
    separately-written reader could easily end up LESS careful than this
    one (e.g. skipping the symlink/size checks), a real gap even before
    considering the race.
    """
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    if os.path.islink(filepath):
        raise IOError(f"Could not read {filepath}: symlinked files are skipped")
    fd = -1
    try:
        fd = os.open(filepath, flags)
        file_stat = os.fstat(fd)
        if not stat.S_ISREG(file_stat.st_mode):
            raise IOError(f"Could not read {filepath}: not a regular file")
        if file_stat.st_size > 500 * 1024 * 1024:  # 500 MB safety limit
            raise IOError(f"File too large ({file_stat.st_size // (1024 * 1024)} MB): {filepath}")
        with os.fdopen(fd, "r", encoding="utf-8-sig", errors="replace") as f:
            fd = -1
            return f.read()
    except OSError as e:
        raise IOError(f"Could not read {filepath}: {e}") from e
    finally:
        if fd != -1:
            try:
                os.close(fd)
            except OSError:
                pass


def normalize(filepath: str, content: Optional[str] = None) -> str:
    """
    Load a file and normalize to transcript format if it's a chat export.
    Plain text files pass through unchanged.

    ``content``, when given, is used directly instead of re-reading
    ``filepath`` -- lets a caller that already read the file (see
    ``_read_source_file``) avoid a second read and the TOCTOU risk of two
    independent reads observing different states of a file that's
    actively being appended to (e.g. convo_miner computing an
    incremental-mining cursor from the same content it just chunked).
    Every existing caller omits this parameter and sees no behavior
    change: the read happens exactly as before.
    """
    if content is None:
        content = _read_source_file(filepath)

    if not content.strip():
        return content

    # Already has > markers — pass through unchanged.
    lines = content.split("\n")
    if sum(1 for line in lines if line.strip().startswith(">")) >= 3:
        return content

    # Try JSON normalization. strip_noise is applied inside the Claude Code
    # JSONL parser (the only format that injects system tags/hook chrome);
    # other formats pass through verbatim.
    ext = Path(filepath).suffix.lower()
    if ext in (".json", ".jsonl") or content.strip()[:1] in ("{", "["):
        normalized = _try_normalize_json(content)
        if normalized:
            return normalized

    return content


def _try_normalize_json(content: str) -> Optional[str]:
    """Try all known JSON chat schemas."""

    normalized = _try_claude_code_jsonl(content)
    if normalized:
        return normalized

    normalized = _try_codex_jsonl(content)
    if normalized:
        return normalized

    normalized = _try_gemini_jsonl(content)
    if normalized:
        return normalized

    normalized = _try_pi_jsonl(content)
    if normalized:
        return normalized

    try:
        data = json.loads(content)
    except json.JSONDecodeError:
        return None

    for parser in (
        _try_gemini_json,
        _try_claude_ai_json,
        _try_chatgpt_json,
        _try_continue_json,
        _try_slack_json,
    ):
        normalized = parser(data)
        if normalized:
            return normalized

    return None


class PositionedClaudeCodeParse(NamedTuple):
    """Result of _try_claude_code_jsonl(..., track_positions=True).

    ``messages`` and ``start_lines`` are parallel lists: ``start_lines[i]``
    is the 0-based index into ``content.strip().split("\\n")`` (interior
    blank lines are counted; matches exactly what this function itself
    iterates) where ``messages[i]`` first began. A merge (tool-result
    folded into the previous assistant turn, multi-turn tool loop folded
    into one assistant message) extends an EXISTING message rather than
    appending a new one, so it does not get its own entry here -- the
    start line stays the line where that message *first* appeared.

    Caveat for callers that persist a start_line and reload it later: the
    leading ``.strip()`` (pre-existing behavior, unrelated to this
    feature) trims leading blank lines/whitespace before the split, so an
    index is relative to the *stripped* content, not raw file bytes. A
    real Claude Code JSONL transcript is never written with leading blank
    lines in practice, so this doesn't matter for that format -- but a
    caller resuming from a stored start_line MUST reproduce the exact same
    ``content.strip().split("\\n")`` transform on re-read, not a raw
    ``readlines()``, or the indices won't line up.
    """

    text: str
    messages: list
    start_lines: list


def _try_claude_code_jsonl(content: str, track_positions: bool = False):
    """Claude Code JSONL sessions.

    ``track_positions=False`` (default, every existing caller): returns
    ``Optional[str]``, unchanged from before this parameter existed.

    ``track_positions=True``: returns ``Optional[PositionedClaudeCodeParse]``
    instead, additionally carrying the raw-line position of each message --
    used by convo_miner's cursor computation (incremental re-mining) to
    identify where the trailing exchange in a transcript actually started
    in the source file. Callers that don't need this keep paying zero cost
    for it: the extra bookkeeping is a few list appends, not a second pass.
    """
    raw_lines = content.strip().split("\n")
    messages = []
    start_lines = []  # parallel to `messages`; only touched on append, never on merge
    tool_use_map = {}  # tool_use_id → tool_name

    for line_index, raw_line in enumerate(raw_lines):
        line = raw_line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict):
            continue
        msg_type = entry.get("type", "")
        message = entry.get("message", {})
        if not isinstance(message, dict):
            continue
        msg_content = message.get("content", "")

        # Build tool_use_map from assistant messages
        if msg_type == "assistant" and isinstance(msg_content, list):
            for block in msg_content:
                if isinstance(block, dict) and block.get("type") == "tool_use":
                    tool_id = block.get("id", "")
                    if tool_id:
                        tool_use_map[tool_id] = block.get("name", "Unknown")

        if msg_type in ("human", "user"):
            # Check if this message is tool_results only (no user text)
            is_tool_only = isinstance(msg_content, list) and all(
                isinstance(b, dict) and b.get("type") == "tool_result" for b in msg_content
            )
            text = _extract_content(msg_content, tool_use_map=tool_use_map)
            # Strip Claude Code system-injected noise per message, never across
            # message boundaries — prevents span-eating.
            if text:
                text = strip_noise(text)
            if text:
                if is_tool_only and messages and messages[-1][0] == "assistant":
                    # Append tool results to the previous assistant message
                    prev_role, prev_text = messages[-1]
                    messages[-1] = (prev_role, prev_text + "\n" + text)
                elif not is_tool_only:
                    messages.append(("user", text))
                    start_lines.append(line_index)
        elif msg_type == "assistant":
            text = _extract_content(msg_content, tool_use_map=tool_use_map)
            if text:
                text = strip_noise(text)
            if text:
                # If previous message is also assistant (multi-turn tool loop),
                # merge into the same assistant turn
                if messages and messages[-1][0] == "assistant":
                    prev_role, prev_text = messages[-1]
                    messages[-1] = (prev_role, prev_text + "\n" + text)
                else:
                    messages.append(("assistant", text))
                    start_lines.append(line_index)

    if len(messages) < 2:
        return None
    transcript = _messages_to_transcript(messages)
    if track_positions:
        return PositionedClaudeCodeParse(
            text=transcript, messages=messages, start_lines=start_lines
        )
    return transcript


def _try_codex_jsonl(content: str) -> Optional[str]:
    """OpenAI Codex CLI sessions (~/.codex/sessions/YYYY/MM/DD/rollout-*.jsonl).

    Uses only event_msg entries (user_message / agent_message) which represent
    the canonical conversation turns. response_item entries are skipped because
    they include synthetic context injections and duplicate the real messages.
    """
    lines = [line.strip() for line in content.strip().split("\n") if line.strip()]
    messages = []
    has_session_meta = False
    for line in lines:
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict):
            continue

        entry_type = entry.get("type", "")
        if entry_type == "session_meta":
            has_session_meta = True
            continue

        if entry_type != "event_msg":
            continue

        payload = entry.get("payload", {})
        if not isinstance(payload, dict):
            continue

        payload_type = payload.get("type", "")
        msg = payload.get("message")
        if not isinstance(msg, str):
            continue
        text = msg.strip()
        if not text:
            continue

        if payload_type == "user_message":
            messages.append(("user", text))
        elif payload_type == "agent_message":
            messages.append(("assistant", text))

    if len(messages) >= 2 and has_session_meta:
        return _messages_to_transcript(messages)
    return None


def _try_gemini_jsonl(content: str) -> Optional[str]:
    """Gemini CLI sessions (~/.gemini/tmp/<project_hash>/chats/session-*.jsonl).

    Schema (per google-gemini/gemini-cli#15292): a session_metadata record
    on the first line, then a stream of ``{"type": "user", "content":
    [{"text": "..."}]}`` and ``{"type": "gemini", "content": [...]}``
    records, with optional ``message_update`` records carrying token
    counts only.

    Detection requires a ``session_metadata`` record so this parser does
    not false-positive against Claude Code or Codex JSONL passed through
    the dispatch chain. Any ``user``/``gemini`` lines that appear before
    ``session_metadata`` are discarded — they are treated as preamble
    noise, not conversational turns. ``message_update`` entries are
    skipped — they have no message text. Multiple text blocks within a
    single message's content array are concatenated in order, separated
    by newlines.
    """
    lines = [line.strip() for line in content.strip().split("\n") if line.strip()]
    messages = []
    has_session_metadata = False
    for line in lines:
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict):
            continue

        entry_type = entry.get("type", "")
        if entry_type == "session_metadata":
            has_session_metadata = True
            continue

        # Discard everything (including user/gemini turns) until the
        # session_metadata sentinel has been seen.
        if not has_session_metadata:
            continue

        if entry_type not in ("user", "gemini"):
            # Skips message_update, system events, anything else.
            continue

        content_blocks = entry.get("content", [])
        if not isinstance(content_blocks, list):
            continue

        parts = []
        for block in content_blocks:
            if not isinstance(block, dict):
                continue
            text = block.get("text", "")
            if isinstance(text, str) and text.strip():
                parts.append(text)
        if not parts:
            continue
        joined = "\n".join(parts)

        if entry_type == "user":
            messages.append(("user", joined))
        else:  # "gemini"
            messages.append(("assistant", joined))

    if len(messages) >= 2 and has_session_metadata:
        return _messages_to_transcript(messages)
    return None


def _try_pi_jsonl(content: str) -> Optional[str]:
    """Pi agent sessions (~/.config/pi/agent/sessions/{cwd}/{timestamp}_{uuid}.jsonl).

    Pi stores sessions as JSONL with a tree-structured message history.
    User messages have role "user" with content as string or [{type, text}] blocks.
    Assistant messages have role "assistant" with content as [{type, text}] blocks
    (may also include "thinking" blocks which are skipped by _extract_content).
    Tool results (role "toolResult") are skipped — operational, not conversation.

    Format documented at github.com/badlogic/pi-mono session.md.
    """
    lines = [line.strip() for line in content.strip().split("\n") if line.strip()]
    messages = []
    has_session_header = False
    for line in lines:
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict):
            continue

        entry_type = entry.get("type", "")
        if entry_type == "session" and "version" in entry:
            has_session_header = True
            continue

        if entry_type != "message":
            continue

        message = entry.get("message", {})
        if not isinstance(message, dict):
            continue

        role = message.get("role", "")
        text = _extract_content(message.get("content", ""))

        if role == "user" and text:
            messages.append(("user", text))
        elif role == "assistant" and text:
            messages.append(("assistant", text))

    if len(messages) >= 2 and has_session_header:
        return _messages_to_transcript(messages)
    return None


def _try_gemini_json(data) -> Optional[str]:
    """Gemini CLI / Google AI Studio JSON sessions.

    Handles three layouts:

    1. **Gemini API contents format** — used by Gemini CLI session files
       (``~/.gemini/sessions/*.json``):
       ``{"contents": [{"role": "user", "parts": [{"text": "..."}]}, ...]}``

    2. **Messages wrapper** — exports that wrap the conversation under a
       ``messages`` key:
       ``{"messages": [{"role": "user", "content": "..."}, {"role": "model", "content": "..."}]}``

    3. **Flat messages list** — top-level array form:
       ``[{"role": "user", "content": "..."}, {"role": "model", "content": "..."}]``

    Gemini uses ``"model"`` as the assistant role (not ``"assistant"``).
    Detection requires at least one ``role="model"`` entry to disambiguate
    from Claude/ChatGPT exports that use ``"assistant"``. This parser is
    placed *before* ``_try_claude_ai_json`` in the dispatch chain so that
    the layout-2 ``{"messages": [...]}`` wrapper does not get silently
    claimed by the Claude parser, which would drop the model turns.
    """
    contents = None

    # Layout 1: {"contents": [...]}
    if isinstance(data, dict) and "contents" in data:
        contents = data["contents"]
    # Layout 2a: {"messages": [...]}
    elif isinstance(data, dict) and "messages" in data:
        contents = data["messages"]
    # Layout 2b: top-level list
    elif isinstance(data, list):
        contents = data

    if not isinstance(contents, list) or len(contents) < 2:
        return None

    messages = []
    has_model_role = False
    for item in contents:
        if not isinstance(item, dict):
            continue
        role = item.get("role", "")

        # Extract text — try "parts" first (Gemini API), then "content" (flat).
        text = ""
        parts = item.get("parts")
        if isinstance(parts, list):
            text_parts = []
            for p in parts:
                if isinstance(p, str):
                    text_parts.append(p)
                elif isinstance(p, dict) and "text" in p:
                    text_parts.append(p["text"])
            text = " ".join(text_parts).strip()
        else:
            text = _extract_content(item.get("content", ""))

        if not text:
            continue

        if role == "user":
            messages.append(("user", text))
        elif role == "model":
            messages.append(("assistant", text))
            has_model_role = True
        elif role == "assistant":
            # Defensive: some hand-crafted exports use "assistant" even
            # for Gemini sessions. Accept but don't flip has_model_role.
            messages.append(("assistant", text))

    # Disambiguator: must have seen at least one role="model" entry.
    # This prevents the Gemini parser from claiming Claude/ChatGPT data.
    if not has_model_role:
        return None

    if len(messages) >= 2:
        return _messages_to_transcript(messages)
    return None


def _try_claude_ai_json(data) -> Optional[str]:
    """Claude.ai JSON export: flat messages list or privacy export with chat_messages."""
    if isinstance(data, dict):
        data = data.get("messages", data.get("chat_messages", []))
    if not isinstance(data, list):
        return None

    # Privacy export: array of conversation objects, each containing its own
    # message list under "chat_messages" or "messages" (both variants seen in the wild).
    if data and isinstance(data[0], dict) and ("chat_messages" in data[0] or "messages" in data[0]):
        transcripts = []
        for convo in data:
            if not isinstance(convo, dict):
                continue
            chat_msgs = convo.get("chat_messages") or convo.get("messages", [])
            messages = _collect_claude_messages(chat_msgs)
            if len(messages) >= 2:
                transcripts.append(_messages_to_transcript(messages))
        if transcripts:
            return "\n\n".join(transcripts)
        return None

    # Flat messages list
    messages = _collect_claude_messages(data)
    if len(messages) >= 2:
        return _messages_to_transcript(messages)
    return None


def _collect_claude_messages(items) -> list:
    """Extract (role, text) pairs from a Claude.ai message list.

    Accepts both ``role`` (API format) and ``sender`` (privacy export) as the
    author field, and falls back to a top-level ``text`` key when the
    ``content`` blocks are empty or absent.
    """
    messages = []
    for item in items:
        if not isinstance(item, dict):
            continue
        role = item.get("role") or item.get("sender", "")
        text = _extract_content(item.get("content", "")) or (item.get("text") or "").strip()
        if role in ("user", "human") and text:
            messages.append(("user", text))
        elif role in ("assistant", "ai") and text:
            messages.append(("assistant", text))
    return messages


def _try_chatgpt_json(data) -> Optional[str]:
    """ChatGPT conversations.json with mapping tree."""
    if not isinstance(data, dict) or "mapping" not in data:
        return None
    mapping = data["mapping"]
    messages = []
    # Find root: prefer node with parent=None AND no message (synthetic root)
    root_id = None
    fallback_root = None
    for node_id, node in mapping.items():
        if node.get("parent") is None:
            if node.get("message") is None:
                root_id = node_id
                break
            elif fallback_root is None:
                fallback_root = node_id
    if not root_id:
        root_id = fallback_root
    if root_id:
        current_id = root_id
        visited = set()
        while current_id and current_id not in visited:
            visited.add(current_id)
            node = mapping.get(current_id, {})
            msg = node.get("message")
            if msg:
                role = msg.get("author", {}).get("role", "")
                content = msg.get("content", {})
                parts = content.get("parts", []) if isinstance(content, dict) else []
                text = " ".join(str(p) for p in parts if isinstance(p, str) and p).strip()
                if role == "user" and text:
                    messages.append(("user", text))
                elif role == "assistant" and text:
                    messages.append(("assistant", text))
            children = node.get("children", [])
            current_id = children[0] if children else None
    if len(messages) >= 2:
        return _messages_to_transcript(messages)
    return None


def _try_slack_json(data) -> Optional[str]:
    """
    Slack channel export: [{"type": "message", "user": "...", "text": "..."}]

    Slack exports are multi-party chats where no speaker is inherently the
    "user" or "assistant".  To preserve exchange-pair chunking (which relies
    on ``>`` markers from the ``user`` role), we still alternate roles, but
    prefix each message with the speaker ID so downstream consumers can
    distinguish the original author.  A provenance header marks the
    transcript as a Slack import.
    """
    if not isinstance(data, list):
        return None
    messages = []
    seen_users = {}
    last_role = None
    for item in data:
        if not isinstance(item, dict) or item.get("type") != "message":
            continue
        raw_user_id = item.get("user", item.get("username", ""))
        # Sanitize speaker ID: strip brackets, newlines, and control chars
        # to prevent chunk-boundary injection via crafted exports
        user_id = re.sub(r"[\[\]\n\r\x00-\x1f]", "_", raw_user_id).strip()
        text = item.get("text", "").strip()
        if not text or not user_id:
            continue
        if user_id not in seen_users:
            # Alternate roles so exchange chunking works with any number of speakers
            if not seen_users:
                seen_users[user_id] = "user"
            elif last_role == "user":
                seen_users[user_id] = "assistant"
            else:
                seen_users[user_id] = "user"
        last_role = seen_users[user_id]
        # Prefix with speaker ID so the original author is preserved
        messages.append((seen_users[user_id], f"[{user_id}] {text}"))
    if len(messages) >= 2:
        return _messages_to_transcript(messages) + _SLACK_PROVENANCE_FOOTER
    return None


def _try_continue_json(data) -> Optional[str]:
    """Continue.dev session JSON (~/.continue/sessions/*.json).

    Sessions contain a ``history`` array of ``{role, content}`` message objects,
    plus optional metadata (``title``, ``sessionId``, ``dateCreated``).
    System messages are skipped.  Tool-call messages (role ``tool``) are
    formatted inline when they contain text content.
    """
    if not isinstance(data, dict) or "history" not in data:
        return None
    history = data["history"]
    if not isinstance(history, list):
        return None

    messages = []
    for item in history:
        if not isinstance(item, dict):
            continue
        role = item.get("role", "")
        content = item.get("content", "")

        # Extract text from string or list-of-blocks content
        if isinstance(content, list):
            parts = []
            for block in content:
                if isinstance(block, dict):
                    if block.get("type") == "text":
                        parts.append(block.get("text", ""))
                elif isinstance(block, str):
                    parts.append(block)
            text = "\n".join(p for p in parts if p).strip()
        elif isinstance(content, str):
            text = content.strip()
        else:
            continue

        if not text:
            continue

        if role == "user":
            messages.append(("user", text))
        elif role == "assistant":
            messages.append(("assistant", text))
        elif role == "tool":
            # Append tool output to the previous assistant turn if possible
            if messages and messages[-1][0] == "assistant":
                prev_role, prev_text = messages[-1]
                messages[-1] = (prev_role, prev_text + "\n" + f"[tool] {text}")
        # Skip system and other roles

    if len(messages) >= 2:
        return _messages_to_transcript(messages)
    return None


def _extract_content(content, tool_use_map: dict = None) -> str:
    """Pull text from content — handles str, list of blocks, or dict.

    Args:
        content: Message content — string, list of content blocks, or dict.
        tool_use_map: Optional mapping of tool_use_id → tool_name, used to
                      select the right formatting strategy for tool_result blocks.
    """
    if isinstance(content, str):
        return content.strip()
    if isinstance(content, list):
        parts = []
        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                block_type = item.get("type")
                if block_type == "text":
                    parts.append(item.get("text", ""))
                elif block_type == "tool_use":
                    parts.append(_format_tool_use(item))
                elif block_type == "tool_result":
                    tid = item.get("tool_use_id", "")
                    tname = (tool_use_map or {}).get(tid, "Unknown")
                    result_content = item.get("content", "")
                    formatted = _format_tool_result(result_content, tname)
                    if formatted:
                        parts.append(formatted)
        return "\n".join(p for p in parts if p).strip()
    if isinstance(content, dict):
        return content.get("text", "").strip()
    return ""


def _format_tool_use(block: dict) -> str:
    """Format a tool_use block into a human-readable one-liner."""
    name = block.get("name", "Unknown")
    inp = block.get("input", {})
    if isinstance(inp, list):
        inp = {}

    if name == "Bash":
        cmd = inp.get("command", "")
        if len(cmd) > 200:
            cmd = cmd[:200] + "..."
        return f"[Bash] {cmd}"

    if name == "Read":
        path = inp.get("file_path", "?")
        offset = inp.get("offset")
        limit = inp.get("limit")
        if offset is not None and limit is not None:
            try:
                return f"[Read {path}:{offset}-{int(offset) + int(limit)}]"
            except (ValueError, TypeError):
                return f"[Read {path}:{offset}+{limit}]"
        return f"[Read {path}]"

    if name == "Grep":
        pattern = inp.get("pattern", "")
        target = inp.get("path") or inp.get("glob") or ""
        return f"[Grep] {pattern} in {target}"

    if name == "Glob":
        pattern = inp.get("pattern", "")
        return f"[Glob] {pattern}"

    if name in ("Edit", "Write"):
        path = inp.get("file_path", "?")
        return f"[{name} {path}]"

    # Unknown tool — serialize input, truncate
    summary = json.dumps(inp, separators=(",", ":"))
    if len(summary) > 200:
        summary = summary[:200] + "..."
    return f"[{name}] {summary}"


_TOOL_RESULT_MAX_LINES_BASH = 20  # head and tail line count
_TOOL_RESULT_MAX_MATCHES = 20  # Grep/Glob cap
_TOOL_RESULT_MAX_BYTES = 2048  # fallback cap for unknown tools


def _format_tool_result(content, tool_name: str) -> str:
    """Format a tool_result based on the originating tool's type.

    Args:
        content: Result text (str) or list of content blocks (list of dicts).
        tool_name: Name of the tool that produced this result.

    Returns:
        Formatted string prefixed with ``→ ``, or empty string if omitted.
    """
    # Normalize list-of-blocks to plain text
    if isinstance(content, list):
        parts = []
        for item in content:
            if isinstance(item, dict) and item.get("type") == "text":
                parts.append(item.get("text", ""))
            elif isinstance(item, str):
                parts.append(item)
        text = "\n".join(parts)
    else:
        text = str(content) if content else ""

    text = text.strip()
    if not text:
        return ""

    # Read/Edit/Write — omit result (content is in palace or git)
    if tool_name in ("Read", "Edit", "Write"):
        return ""

    lines = text.split("\n")

    # Bash — head + tail
    if tool_name == "Bash":
        n = _TOOL_RESULT_MAX_LINES_BASH
        if len(lines) <= n * 2:
            return "→ " + "\n→ ".join(lines)
        head = lines[:n]
        tail = lines[-n:]
        omitted = len(lines) - 2 * n
        return (
            "→ "
            + "\n→ ".join(head)
            + f"\n→ ... [{omitted} lines omitted] ..."
            + "\n→ "
            + "\n→ ".join(tail)
        )

    # Grep/Glob — cap matches
    if tool_name in ("Grep", "Glob"):
        cap = _TOOL_RESULT_MAX_MATCHES
        if len(lines) <= cap:
            return "→ " + "\n→ ".join(lines)
        kept = lines[:cap]
        remaining = len(lines) - cap
        return "→ " + "\n→ ".join(kept) + f"\n→ ... [{remaining} more matches]"

    # Unknown — byte cap
    if len(text) > _TOOL_RESULT_MAX_BYTES:
        return "→ " + text[:_TOOL_RESULT_MAX_BYTES] + f"... [truncated, {len(text)} chars]"
    return "→ " + text


def _messages_to_transcript(messages: list, spellcheck: bool = True) -> str:
    """Convert [(role, text), ...] to transcript format with > markers."""
    if spellcheck:
        try:
            from mempalace.spellcheck import spellcheck_user_text

            _fix = spellcheck_user_text
        except ImportError:
            _fix = None
    else:
        _fix = None

    lines = []
    i = 0
    while i < len(messages):
        role, text = messages[i]
        if role == "user":
            if _fix is not None:
                text = _fix(text)
            lines.append(f"> {text}")
            if i + 1 < len(messages) and messages[i + 1][0] == "assistant":
                lines.append(messages[i + 1][1])
                i += 2
            else:
                i += 1
        else:
            lines.append(text)
            i += 1
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python normalize.py <filepath>")
        sys.exit(1)
    filepath = sys.argv[1]
    result = normalize(filepath)
    quote_count = sum(1 for line in result.split("\n") if line.strip().startswith(">"))
    print(f"\nFile: {os.path.basename(filepath)}")
    print(f"Normalized: {len(result)} chars | {quote_count} user turns detected")
    print("\n--- Preview (first 20 lines) ---")
    print("\n".join(result.split("\n")[:20]))
